import React, { useRef, useEffect, useCallback } from 'react';
import type { ResolvedMentionReference } from './types';
import { escapeHtml, escapeRegex, extractText, getCaretOffset, setCaretOffset } from './utils';

interface ContentEditablePromptProps {
  value: string;
  placeholder?: string;
  resolvedReferences: ResolvedMentionReference[];
  onChange: (value: string, cursorOffset: number) => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onKeyDown?: (event: React.KeyboardEvent<HTMLDivElement>) => void;
  onKeyUp?: (event: React.KeyboardEvent<HTMLDivElement>) => void;
  onClick?: (event: React.MouseEvent<HTMLDivElement>) => void;
  className?: string;
}

export const ContentEditablePrompt = React.forwardRef<HTMLDivElement, ContentEditablePromptProps>(({
  value,
  placeholder,
  resolvedReferences,
  onChange,
  onFocus,
  onBlur,
  onKeyDown,
  onKeyUp,
  onClick,
  className,
}, forwardedRef) => {
  const innerRef = useRef<HTMLDivElement>(null);
  const containerRef = (forwardedRef as React.MutableRefObject<HTMLDivElement>) || innerRef;
  const lastEmittedValue = useRef<string>(value);
  const emittedValuesQueue = useRef(new Set<string>());
  const prevRefsKey = useRef<string>('');

  const generateHtml = useCallback((text: string, refs: ResolvedMentionReference[]) => {
    let html = escapeHtml(text);
    html = html.replace(/\n/g, '<br>');

    const sortedRefs = [...refs].sort((a, b) => b.mention.length - a.mention.length);

    sortedRefs.forEach(ref => {
      const escapedMention = escapeRegex(ref.mention);
      const regex = new RegExp(`(${escapedMention})(?!\\w)`, 'g');

      const thumbUrl = ref.thumbUrl || ref.url;
      const finalThumbUrl = ref.kind === 'video' ? (thumbUrl.includes('#') ? thumbUrl : `${thumbUrl}#t=0.001`) : thumbUrl;

      const thumbHtml = ref.kind === 'video'
        ? `<video src="${finalThumbUrl}" class="lab-prompt-inline-preview-thumb" muted playsinline preload="metadata"></video>`
        : `<img src="${finalThumbUrl}" alt="${escapeHtml(ref.name)}" class="lab-prompt-inline-preview-thumb" />`;

      const chipHtml =
        `<span contenteditable="false" data-mention-key="${ref.mention.slice(1)}" class="lab-prompt-inline-preview-item" style="margin: 0 4px; cursor: default;">` +
        thumbHtml +
        `<span class="lab-prompt-inline-preview-label">${escapeHtml(ref.name)}</span>` +
        `<button type="button" class="lab-prompt-inline-preview-delete lab-prompt-inline-preview-delete--always" data-delete-mention="${ref.mention.slice(1)}" aria-label="Remove reference">×</button>` +
        `</span>`;

      html = html.replace(regex, chipHtml);
    });

    return html;
  }, []);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const refsKey = resolvedReferences.map(r => r.mention + r.url).join('|');
    const refsChanged = refsKey !== prevRefsKey.current;
    prevRefsKey.current = refsKey;

    const currentDomText = extractText(el);

    // If this incoming value was generated by our own typing, and refs haven't changed,
    // NO NEED to overwrite the HTML. The DOM is either currently at this value or ahead of it!
    if (!refsChanged && (value === currentDomText || emittedValuesQueue.current.has(value))) {
      // Just keep track of the latest acknowledged value.
      lastEmittedValue.current = value;
      // We can remove it from the queue if we want, but keeping it is fine (it resets on external changes)
      return;
    }

    // Since we're overwriting the DOM, this value is explicitly from the outside,
    // OR mentions have changed. We must wipe the queue to reset syncing.
    emittedValuesQueue.current.clear();
    lastEmittedValue.current = value;

    const offset = document.activeElement === el ? getCaretOffset(el) : null;
    el.innerHTML = generateHtml(value, resolvedReferences);
    
    if (offset !== null) {
      setCaretOffset(el, offset);
    }
  }, [value, resolvedReferences, generateHtml, containerRef]);

  const handleInput = () => {
    const el = containerRef.current;
    if (!el) return;
    const text = extractText(el);
    if (text !== lastEmittedValue.current) {
      lastEmittedValue.current = text;
      emittedValuesQueue.current.add(text);
      const offset = getCaretOffset(el);
      onChange(text, offset);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (onKeyDown) onKeyDown(e);
  };

  const handleKeyUp = (e: React.KeyboardEvent<HTMLDivElement>) => {
    // Do NOT call handleInput() here — onInput already handles text changes.
    // onKeyUp is only for cursor-movement detection (arrow keys, etc.) via the parent handler.
    if (onKeyUp) onKeyUp(e);
  };

  const handleClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const target = e.target as HTMLElement;
    const deleteBtn = target.closest('.lab-prompt-inline-preview-delete');
    if (deleteBtn) {
      e.preventDefault();
      e.stopPropagation();
      const chip = target.closest('[data-mention-key]');
      if (chip) {
        chip.remove();
        handleInput();
      }
      return;
    }

    if (onClick) onClick(e);
    const el = containerRef.current;
    if (el) {
      onChange(extractText(el), getCaretOffset(el));
    }
  };

  return (
    <div
      ref={containerRef}
      contentEditable
      className={className}
      onInput={handleInput}
      onKeyDown={handleKeyDown}
      onKeyUp={handleKeyUp}
      onClick={handleClick}
      onFocus={onFocus}
      onBlur={onBlur}
      role="textbox"
      aria-multiline="true"
      aria-placeholder={placeholder}
      data-placeholder={placeholder}
      suppressContentEditableWarning
    />
  );
});

